name: spaceship-titanic
channels: 
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - kaggle [-c conda-forge]
  - ipykernel
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn